/*GENERATED BY OBNC 0.13.1*/

#ifndef Readline_h
#define Readline_h

#include <obnc/OBNC.h>

#define Readline_Readline_ oberon2_Readline_Readline_
int Readline_Readline_(const char prompt_[], OBNC_LONGI int prompt_len, char line_[], OBNC_LONGI int line_len);

#define Readline_AddHistory_ oberon2_Readline_AddHistory_
void Readline_AddHistory_(const char line_[], OBNC_LONGI int line_len);

#define Readline_Init oberon2_Readline_Init
void Readline_Init(void);

#endif
