import("libm3")

if defined("Test")
  module("Util")
  implementation("Test")
  program("Test")
else
  import_lib("readline", "/usr/lib")
  module("Readline")
  implementation("Repl")
  program("Repl")
end
